import './globals.css'
import Nav from "../../components/navbar";
import Github from '../../components/github';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#0E131B] flex h-full'>
      <Nav/>

        {children}
        {/* <Github/> */}

       
        
        </body>
    </html>
  )
}
