/** @format */

import "./globals.css";
import Nav from "../../components/navbar";
import Github from "../../public/assets/git.png";
import bg from "../../public/assets/bg.png";
import Image from "next/image";



// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#0E131B] flex h-full">
      <div className="bg-svg-wrap">
        <div className="bg-svg"></div>
      </div>
      <Image src={bg} alt="" className="fixed top-0 right-0 -z-10 opacity-30" width={650}/>
      <Image src={bg} alt="" className="fixed left-20 bottom-0 -z-10 opacity-30" width={650}/>

        <Nav />
        {children}
        <div className="mt-auto pr-20">
          <Image src={Github} alt="" />
        </div>
      </body>
    </html>
  );
}
